### ISSUE TITLE
Course Details

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#12]
![image](https://github.com/Tri-Luan/KL/assets/91579383/60837ff5-f7ff-45df-86e2-0b52f7db3419)

Thay màu chữ progressing

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/24cf8e59-4e4f-4f80-ae3b-d062d2f203d7)
