### ISSUE TITLE
Sắp xếp các bài luyện tập chưa tương thích với kích thước màn hình

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#15]
![image](https://github.com/Tri-Luan/KL/assets/91579383/641373fe-9d05-4f49-88d2-8310f54b7b44)

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/a58dc09f-d93d-4213-bc32-dc203aed18ac)
