### ISSUE TITLE
Course Comment

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#16]
![image](https://github.com/Tri-Luan/KL/assets/91579383/c7c846dc-ab3d-4ba8-b5e5-8f8825fc7a5f)

Xóa bớt nút reply ở phần reply comment

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/b0ea8e7f-0f25-4b8e-8431-3f635ab9defc)
