### ISSUE TITLE
Logout Error

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#2]
Khi log out chưa remove bỏ cookies

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/046be480-2755-487d-aea1-3e4f9d853c09)
![image](https://github.com/Tri-Luan/KL/assets/62927098/c128889e-6147-44e5-aa5c-61b2245987b4)

**Comment by vitramkhoi2044** [comment]
![image](https://github.com/Tri-Luan/KL/assets/91579383/05aa4337-8f94-4593-8eb4-cfd82cec5003)

Logout xong k load lại được main page
