### ISSUE TITLE
Lesson management

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#20]
![image](https://github.com/Tri-Luan/KL/assets/91579383/3f7cd9d1-8743-4d28-bcd0-fcfe26be3a2c)

Thêm **button** cho phép người dùng back về **chapter management**

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/39b81d1d-aea1-4268-86df-64b8c92922bc)
