### ISSUE TITLE
Chapter management

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#21]
![image](https://github.com/Tri-Luan/KL/assets/91579383/7e880fcc-2420-4eeb-96e5-b8914e94af02)

Thêm **button** cho phép người dùng back về **course management**

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/02429eda-a354-4f54-908b-6593defdbaf6)
