### ISSUE TITLE
Update practice

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#22]
![image](https://github.com/Tri-Luan/KL/assets/91579383/5c1222c8-38e6-4d24-aacc-594790ecb2a6)

Load **thiếu** thông tin **testcase** và **content**

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/777c1037-bf12-4c6f-a570-cfbd9c26d3a4)
