### ISSUE TITLE
Disscussion Comment

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#23]
![image](https://github.com/Tri-Luan/KL/assets/91579383/4620bb60-f731-4b0b-b0c5-04b5e0e39b9a)

Ẩn button **DELETE** khi không phải user comment và button **REPLY** ở phần reply comment

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/01515fe7-55e9-4446-af20-46f17aa44622)
