### ISSUE TITLE
Course Comment

### ISSUE THREAD

**Issue by vitramkhoi2044** [Tri-Luan/KL#8]
![image](https://github.com/Tri-Luan/KL/assets/91579383/abb367dc-d857-40a1-85d8-313f299b410c)

Thêm confirmation khi xóa comment

Thêm refetch api khi chuyển sang tab comments

**Comment by Tri-Luan** [comment]
![image](https://github.com/Tri-Luan/KL/assets/62927098/774d9a80-69ab-4a96-9156-70d1820d1bd8)
